Vagrant.configure(2) do |config|
    config.vm.provider "hyperv"
	config.vm.define "devops-box" do |devbox|
		devbox.vm.box = "generic/ubuntu1804"
      		devbox.vm.provision "shell", path: "scripts/install.sh"
	end
end
